name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf build-essential libtool
          pip install --upgrade pip setuptools wheel
          pip install cython virtualenv

      - name: Install Buildozer
        run: |
          pip install --user buildozer

      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: |
          export PATH=$HOME/.local/bin:$PATH
          buildozer -v android debug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
